import Head from "next/head";
import { ChevronLeftIcon, ChevronRightIcon } from "@heroicons/react/solid";
import workspace from "../loottie/workspace";

import Lottie from "react-lottie";
import { useEffect, useState } from "react";
import { projects } from "../utils/projectsData";
import Link from "next/link";
import Footer from "../components/footer";
import Header from "../components/header";
import Image from "next/image";
import { useTheme } from "next-themes";
import React from "react";
// Import Swiper React components
import { Swiper, SwiperSlide, useSwiper } from "swiper/react";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

// import required modules
import { Navigation, Pagination, Mousewheel, Keyboard } from "swiper";
import { Carousel } from "flowbite-react";

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { theme } = useTheme();

  const workspaceSettings = {
    loop: true,
    autoplay: true,
    animationData: workspace,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };
  useEffect(() => {
    setMounted(true);
    if (mounted) {
      document
        .getElementById("carousel")
        .children[3].firstChild.classList.add("carouselBtn");
      document
        .getElementById("carousel")
        .children[2].lastChild.classList.add("carouselBtn");
    }

    return () => setMounted(false);
  }, [mounted]);

  if (!mounted) return null;

  return (
    <>
      <div className="  ">
        <Head>
          <title>Solomon Emetonjo</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        {/* header */}
        <Header />

        {/* first */}
        <main className=" p-2 my-16 md:mt-24 lg:mt-40 lg:h-[80vh] mx-auto max-w-6xl  2xl:h-fit   ">
          <div className="items-center flex flex-col w-full   lg:flex-row md:justify-between   ">
            <div className="max-w-lg ">
              <p
                className="
              mb-3 text-base text-center lg:text-start md:text-xl leading-6 font-poppins"
              >
                {" "}
                Hi, I&#39;m Solomon, I enjoy helping startups or individuals
                achieve their project goals with my web development skills.
              </p>
              <p
                className={`lg:text-start title  text-3xl md:text-4xl text-center font-bold lg:text-5xl`}
              >
                Permit me to make the world a better place with
                <span className="text-[#dba713]"> Codes</span>.
              </p>
              <Link href={"/contact"}>
                <p
                  tabIndex={0}
                  className=" cursor-pointer  hover:bg-green-700  bg-green-900   text-[#f4f4f4]  text-lg p-3 w-60 text-center mt-10 mx-auto lg:mx-0 font-bold rounded-xl"
                >
                  Hire Me
                </p>
              </Link>
            </div>
            <div className="cursor-text self-center z-10 w-full max-w-sm lg:max-w-md lg:mt-0   mt-10">
              <Lottie options={workspaceSettings} />
            </div>
          </div>
        </main>

        {/* propjects */}
        <div
          className=" mt-40   text-base  leading-5 max-w-6xl mx-auto   "
          id="projects"
        >
          <h2
            className={`font-bold text-4xl  title  text-center md:text-5xl mb-10`}
          >
            Showcase
          </h2>

          <div className="h-[450px] sm:h-64 xl:h-80 2xl:h-96  ">
            <Carousel slideInterval={5000} id="carousel">
              {projects.map((project) => {
                return (
                  <div
                    key={project.id}
                    className="flex flex-col sm:flex-row  mx-auto w-full justify-between items-center p-2   "
                  >
                    <div className=" sm:max-w-xs md:max-w-md lg:max-w-lg  p-16 ">
                      <div
                        className={`sm:hidden relative m-5 h-52 w-80 mx-auto`}
                      >
                        <Image
                          alt={project.alt}
                          layout="fill"
                          loading={"eager"}
                          src={project.thumbnail}
                          className="hover:scale-105   "
                        />
                      </div>
                      <h2 className=" text-lg lg:2xl: font-bold">
                        {project.name}
                      </h2>
                      <p className="leading-6  text-base line-clamp-3 sm:line-clamp-6 ">
                        {project.description}
                      </p>
                      <p className=" italic text-sm mt-2   "> {project.tags}</p>
                      <div className="mt-5">
                        <a
                          href={project.url}
                          className=" cursor-pointer hover:bg-green-700  bg-green-900   text-[#f4f4f4]    text-sm lg:text-lg p-3 w-fit lg:w-40 text-center  mx-auto lg:mx-0 font-medium rounded-xl"
                        >
                          Live view
                        </a>
                      </div>
                    </div>

                    <div
                      className={`hidden sm:inline-flex   relative m-10 sm:mr-16    sm:h-52 sm:w-64  lg:h-64 lg:w-96`}
                    >
                      <Image
                        alt={project.alt}
                        layout="fill"
                        loading={"eager"}
                        objectFit="cover"
                        src={project.thumbnail}
                        className="hover:scale-105  border-2 "
                      />
                    </div>
                  </div>
                );
              })}
            </Carousel>
          </div>
        </div>

        <div
          className=" flex mt-16 lg:mt-36 justify-between mx-auto max-w-lg   lg:max-w-4xl   w-full text-center lg:text-start  flex-col lg:flex-row "
          id="about"
        >
          <div className=" hidden lg:inline-flex lg:self-center ">
            <Image
              width={150}
              layout="fixed"
              alt="solomon emetonjo"
              height={150}
              objectFit="cover"
              quality={100}
              loading={"eager"}
              src={"/images/rufans.png"}
              className="rounded-full "
            />
          </div>

          <div className="max-w-3xl space-y-5 lg:space-x-10 leading-6 text-base  md:text-xl  ">
            <h1
              className={`font-bold text-4xl  lg:text-center md:text-5xl title `}
            >
              About Me
            </h1>
            <p className="">
              I specialize in front-end web development using Reactjs and am
              experienced in creating dynamic, user-friendly websites. I am
              proficient in using Tailwindcss to enhance the visual appeal of my
              projects. My goal is to build engaging and intuitive interfaces
              that provide a positive experience for users.
            </p>
            <p>
              I&#39;m now embarking on a Blockchain development journey while
              working with Nextjs to communicate with smart contracts.
            </p>

            <div className="flex items-center gap-x-5 mx-auto lg:mx-0 max-w-xs text-start">
              <div className=" lg:hidden ">
                <Image
                  width={48}
                  height={48}
                  alt="solomon emetonjo"
                  loading={"eager"}
                  src={"/images/rufans.png"}
                  className="rounded-full "
                />
              </div>
              <div>
                <h2 className="font-bold text-xl ">Solomon Emetonjo</h2>
                <p className=" ">Frontend Web Developer</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
